In [1]:
%load_ext rpy2.ipython

In [ ]:
%%R
library(stringr)

lapply(c("dplyr","Seurat","HGNChelper","openxlsx"), library, character.only = T)

load('../data/reference.RData')

sample_meta<-'AD_HS_00001	Molecular characterization of selectively vulnerable neurons in Alzheimerâ€™s Disease	20	H.Sapiens	AD	Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Superior frontal gyrus;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex;Entorhinal cortex	Braak:0;0;0;2;2;2;2;6;6;6;0;0;0;2;2;2;2;6;6;6	ExcitatoryNeuron;InhibitoryNeuron;Oligodendrocyte;OPC;Astrocyte;Microglia;Endothelia;Pericyte	GSE147528	Single-nucleus RNA-seq	10x Genomics	Male	60;50;71;72;87;91;77;82;72;82;60;50;71;72;87;91;77;82;72;82	SRR11422700;SRR11422701;SRR11422702;SRR11422703;SRR11422704;SRR11422705;SRR11422706;SRR11422707;SRR11422708;SRR11422709;SRR11422710;SRR11422711;SRR11422712;SRR11422713;SRR11422714;SRR11422715;SRR11422716;SRR11422717;SRR11422718;SRR11422719'
split_meta<-unlist(strsplit(sample_meta, '\t'))
samples<-unlist(strsplit(split_meta[14],';'))
disease<-rep(split_meta[5],length(samples))
stage<-unlist(strsplit(unlist(strsplit(split_meta[7],':'))[2],';'))
gender<-rep(split_meta[12],length(samples))
age<-unlist(strsplit(split_meta[13],';'))

sample_meta<-data.frame(samples=samples,disease=disease,stage=stage,gender=gender,age=age)
sample_meta[sample_meta$stage=='0','disease']<-'Control'
rownames(sample_meta)<-sample_meta$samples

# args <- commandArgs(trailingOnly=TRUE)
args<-c('../data/3/scte','../data/3/cell_umap.txt','SRR11422700','/home/wdeng3/workspace/software/sc-type','../../universal_data/rmsk/rmsk_GRCh38.txt')
data_path<-args[1]
out_path<-args[2]
sample_tag<-args[3]
sctype_path<-args[4]
rmsk_path<-args[5]
rmsk<-read.table(rmsk_path,sep='\t',header=F)
to_remove<-unlist(rmsk[!(rmsk$V12 %in% c('LINE','SINE','LTR')),'V11'])
to_remove<-str_replace_all(to_remove,'-','\\.')

reps<-unlist(rmsk[rmsk$V12 %in% c('LINE','SINE','LTR'),'V11'])
reps<-str_replace_all(reps,'-','\\.')

create_seurat<-function(sample_tag){
    ## load data
    scte.data <- t(read.csv(paste0(data_path,'/',sample_tag,'/',sample_tag,'.csv'),check.names=F, row.names = 1))
    # remove repeats from gene expression matrix

    scte.gene<-scte.data[!(row.names(scte.data) %in% to_remove),]
    # normalize and scale data
    scte <- CreateSeuratObject(counts = scte.gene, project = sample_tag, min.cells = 3, min.features = 200)
    # normalize data
    scte[["percent.mt"]] <- PercentageFeatureSet(scte, pattern = "^MT.|^MT-")
    scte <- subset(scte, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
    scte <- SCTransform(scte, vars.to.regress = "percent.mt", verbose = FALSE)

    cell_meta<-scte@meta.data
    cell_meta$disease<-sample_meta[cell_meta$orig.ident,'disease']

    cell_meta$stage<-sample_meta[cell_meta$orig.ident,'stage']
    cell_meta$gender<-sample_meta[cell_meta$orig.ident,'gender']
    cell_meta$age<-sample_meta[cell_meta$orig.ident,'age']
    scte@meta.data<-cell_meta
    scte
}

scte<-create_seurat(sample_tag)

scte <- FindVariableFeatures(scte, selection.method = "vst", nfeatures = 2000)
# scale and run PCA
scte <- ScaleData(scte, features = rownames(scte))
scte <- RunPCA(scte, features = VariableFeatures(object = scte))

sdv<-Stdev(scte,reduction='pca')
sdv<-sdv[sdv>2]
npca<-length(sdv)

scte <- FindNeighbors(scte, dims = 1:npca)
scte <- FindClusters(scte, resolution = 0.8)
scte <- RunUMAP(scte, dims = 1:npca)


scte.anchors <- FindTransferAnchors(reference = reference, query = scte,
    dims = 1:30, reference.reduction = "pca")
scte.query <- MapQuery(anchorset = scte.anchors, reference = reference, query = scte,
    refdata = list(celltype = "broad.cell.type"), reference.reduction = "pca", reduction.model = "umap")
cell_meta<-scte.query@meta.data

cell_meta$UMAP_1<-scte.query@reductions[['umap']]@cell.embeddings[,1]
cell_meta$UMAP_2<-scte.query@reductions[['umap']]@cell.embeddings[,2]
scte.query@meta.data<-cell_meta
write.table(cell_meta,out_path,sep='\t',quote=F,row.names=T)

## get gene expression from scte_query
scte.query.gene<-as.data.frame(t(as.data.frame(GetAssayData(scte.query, slot = "data"))))
scte.query.gene$UMAP_1<-scte.query@meta.data$UMAP_1
scte.query.gene$UMAP_2<-scte.query@meta.data$UMAP_2
write.table(scte.query.gene,'../data/3/cell_exp.txt',sep='\t',quote=F,row.names=T)

In [3]:
import pandas as pd
import numpy as np
from scipy.stats import mannwhitneyu
import os

file_list=[x for x in os.listdir('../data/all_datasets') if x.endswith('.cell_exp.txt')]
rmsk=pd.read_table('../../universal_data/rmsk/rmsk_GRCh38.txt',sep='\t',header=None)
rtes=rmsk[rmsk[11].isin(['LINE','SINE','LTR'])][10].unique()
datasets=list(set([x.split('.')[0] for x in file_list]))
datasets.sort()
cell_types=['Ex','Ast','Mic','OPC','Oli','In']
import random
def get_dataset(dataset):
    print(dataset)
    randint=random.randint(0,1000)
    print(f'loading data: {dataset}_{randint}')
    results=[]
    dt_ls=[x for x in file_list if x.startswith(dataset)]
    cell_exp=pd.read_table('../data/all_datasets/'+dt_ls[0],index_col=0)
    if len(dt_ls) >1:
        cell_umap=pd.read_table(f'../data/all_datasets/{dataset}.1.cell_umap.txt',index_col=0)
        for i in range(1,len(dt_ls)):
            cell_exp=pd.concat([cell_exp,pd.read_table('../data/all_datasets/'+dt_ls[i],index_col=0)])
            cell_umap=pd.concat([cell_umap,pd.read_table(f'../data/all_datasets/{dataset}.{i}.cell_umap.txt',index_col=0)])
    else:
        cell_umap=pd.read_table('../data/all_datasets/'+dataset+'.cell_umap.txt',index_col=0)
    
    cell_umap['predicted.celltype'] = cell_umap['predicted.celltype'].replace(
        'Opc', 'OPC')
    for i in range(cell_umap.shape[0]):
        if cell_umap.iloc[i,1] =='Stage_0':
            cell_umap.iloc[i,1]='Control'
        if cell_umap.iloc[i,1] !='Control':
            cell_umap.iloc[i,1]=cell_umap.iloc[i,7].split('_')[0]

    cell_exp=cell_exp.loc[:,[x for x in cell_exp.columns if x in rtes]]
    ## disease v.s. control
    print('extracting disease v.s. control')
    disease=dataset.split('_')[0]
    for cell in cell_types:
        disease_list=cell_umap.loc[(cell_umap['predicted.celltype']==cell) & (cell_umap['Diagnosis']!='Control'),:].index
        control_list=cell_umap.loc[(cell_umap['predicted.celltype']==cell) & (cell_umap['Diagnosis']=='Control'),:].index
        for te in rtes:
            if te in cell_exp.columns:
                disease_exp=np.exp(cell_exp.loc[disease_list,te])
                control_exp=np.exp(cell_exp.loc[control_list,te])
                pval=mannwhitneyu(disease_exp,control_exp)[1]
                c1_median=np.median(disease_exp)
                c2_median=np.median(control_exp)
                fc=np.log2(np.median(disease_exp)/np.median(control_exp))
                results.append([te,f'{disease} v.s. Control',dataset,cell,'NA',np.log(c1_median),np.log(c2_median),fc,pval])
    ## cell v.s. cell
    print('extracting cell v.s. cell')
    for cell1 in cell_types:
        for cell2 in cell_types:
            if not cell1==cell2:
                for condition in [disease,'Control']:
                    cell1_list=cell_umap.loc[(cell_umap['predicted.celltype']==cell1) & (cell_umap['Diagnosis']==condition),:].index
                    cell2_list=cell_umap.loc[(cell_umap['predicted.celltype']==cell2) & (cell_umap['Diagnosis']==condition),:].index
                    for te in rtes:
                        if te in cell_exp.columns:
                            cell1_exp=np.exp(cell_exp.loc[cell1_list,te])
                            cell2_exp=np.exp(cell_exp.loc[cell2_list,te])
                            pval=mannwhitneyu(cell1_exp,cell2_exp)[1]
                            c1_median=np.median(cell1_exp)
                            c2_median=np.median(cell2_exp)
                            fc=np.log2(np.median(cell1_exp)/np.median(cell2_exp))
                            results.append([te,f'{cell1} v.s. {cell2}',dataset,'NA',condition,np.log(c1_median),np.log(c2_median),fc,pval])
    return results
from multiprocessing import Pool
pool = Pool(20)
print(datasets)
ret=pool.map(get_dataset,datasets)
pool.close()
pool.join()

final_result=[]
for i in ret:
    final_result.extend(i)
final_result=pd.DataFrame(final_result,columns=['TE','Comparison','Dataset','Cell','Condition','log2_median1','log2_median2','log2_FC','pval'])
final_result.to_csv('../data/all_datasets/ret_compare.txt',sep='\t',index=False)

/tmp/ipykernel_307/3827847824.py:7: DtypeWarning: Columns (0,1,2,3,4,6,7,8,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  rmsk=pd.read_table('../../universal_data/rmsk/rmsk_GRCh38.txt',sep='\t',header=None)

AD_HS_00003AD_HS_00006
AD_HS_00002AD_HS_00005AD_HS_00008AD_HS_00004MS_HS_00001MS_HS_00002PD_HS_00001AD_HS_00001
loading data: AD_HS_00003_112AD_HS_00007







loading data: AD_HS_00006_52

loading data: AD_HS_00004_998loading data: AD_HS_00002_801loading data: AD_HS_00005_469loading data: AD_HS_00008_588loading data: MS_HS_00001_159loading data: PD_HS_00001_174loading data: MS_HS_00002_133loading data: AD_HS_00001_55


loading data: AD_HS_00007_205






['AD_HS_00001', 'AD_HS_00002', 'AD_HS_00003', 'AD_HS_00004', 'AD_HS_00005', 'AD_HS_00006', 'AD_HS_00007', 'AD_HS_00008', 'MS_HS_00001', 'MS_HS_00002', 'PD_HS_00001']
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting disease v.s. control
extracting cell v.s. cell
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell
extracting disease v.s. control
extracting cell v.s. cell

In [5]:
te_exp=open(out_path+'/te_exp_boxplot.sql','w')

te_exp.write('''use scARE;
    DROP TABLE IF EXISTS `TE_EXP_BOXPLOT`;
    CREATE TABLE `TE_EXP_BOXPLOT` (
        ID int(11) NOT NULL AUTO_INCREMENT,
        CELL_TYPE varchar(255) NOT NULL,
        CELL_NUM int(11) NOT NULL,
        DATASET varchar(255) NOT NULL,
        DISEASE varchar(255) NOT NULL,
        TE varchar(255) NOT NULL,
        MAX float NOT NULL,
        MIN float NOT NULL,
        Q1 float NOT NULL,
        MEDIAN float NOT NULL,
        Q3 float NOT NULL,
        PRIMARY KEY (ID));
        set autocommit=0;\n''')

result=pd.DataFrame(result,columns=['cell_type','cell_num','dataset','disease','te','max','min','q1','median','q3'])
result['cell_type']=result['cell_type'].apply(lambda x:'"'+x+'"')
result['dataset']=result['dataset'].apply(lambda x:'"'+x+'"')   
result['disease']=result['disease'].apply(lambda x:'"'+x+'"')
result['te']=result['te'].apply(lambda x:'"'+x+'"')
result.fillna(-1,inplace=True)

count=0
values_list=[]
template='INSERT INTO `TE_EXP_BOXPLOT` (CELL_TYPE,CELL_NUM,DATASET,DISEASE,TE,MAX,MIN,Q1,MEDIAN,Q3) VALUES {values};\n'
for i in range(result.shape[0]):
    if count==2000:
        te_exp.write(template.format(values=','.join(values_list)))
        count=0
        values_list=[]
    values_list.append('('+','.join([str(x) for x in result.iloc[i,:]])+')')
    count+=1

if count>0:
    te_exp.write(template.format(values=','.join(values_list)))
te_exp.write('commit;')
te_exp.close()

432366

In [6]:
final_result.head()

,TE,Comparison,Dataset,Cell,Condition,log2_median1,log2_median2,log2_FC,pval
0,L1P5,AD v.s. Control,AD_HS_00001,Ex,NA,0.000000,0.000000,0.000000,1.374865e-02
1,AluY,AD v.s. Control,AD_HS_00001,Ex,NA,5.966901,5.996269,-0.042369,2.691087e-11
2,L1MB5,AD v.s. Control,AD_HS_00001,Ex,NA,2.297829,2.315329,-0.025247,5.616159e-04
3,AluSc,AD v.s. Control,AD_HS_00001,Ex,NA,4.666867,4.714000,-0.067998,3.252002e-14
4,HAL1,AD v.s. Control,AD_HS_00001,Ex,NA,3.322802,3.349713,-0.038824,3.574014e-04

In [5]:
control_list

Index([], dtype='object')

In [6]:
cell_umap

,predicted.celltype,Diagnosis,stage,msex,age_death,UMAP_1,UMAP_2,dataset
SRR11422700_AAAAAACTCCAACCAA,Ex,Stage_0,NaN,NaN,NaN,3.892934,6.910680,AD_HS_00003
SRR11422700_AAAACAACAATGGAAT,Ex,Stage_0,NaN,NaN,NaN,4.549984,6.959525,AD_HS_00003
SRR11422700_AAAACTCAGACAAAGG,Ex,Stage_0,NaN,NaN,NaN,3.793271,6.914708,AD_HS_00003
SRR11422700_AAAACTCAGCGTTTAC,Ex,Stage_0,NaN,NaN,NaN,5.781046,6.445986,AD_HS_00003
SRR11422700_AAAACTCTCCAAACAC,Ex,Stage_0,NaN,NaN,NaN,7.880208,7.098388,AD_HS_00003
...,...,...,...,...,...,...,...,...
SRR11422709_TTTGTCACATGAACCT,Oli,Stage_6,NaN,NaN,NaN,-6.770343,1.267352,AD_HS_00003
SRR11422709_TTTGTCAGTCACCTAA,Ex,Stage_6,NaN,NaN,NaN,1.176651,4.918381,AD_HS_00003
SRR11422709_TTTGTCAGTGTGGTTT,Oli,Stage_6,NaN,NaN,NaN,-6.788431,1.532442,AD_HS_00003
SRR11422709_TTTGTCATCACGGTTA,In,Stage_6,NaN,NaN,NaN,3.986920,0.141141,AD_HS_00003
SRR11422709_TTTGTCATCGCGGATC,Ex,Stage_6,NaN,NaN,NaN,2.906748,5.158192,AD_HS_00003

In [ ]:
# ## assign cell type according to ScType tuturial

## load sc type and database
# source(paste0(sctype_path,"/R/gene_sets_prepare.R"))
# source(paste0(sctype_path,"/R/sctype_score_.R"))
# gs_list = gene_sets_prepare(paste0(sctype_path,'/ScTypeDB_full.xlsx'), "Brain" )
# # get cell-type by cell matrix
# es.max = sctype_score(scRNAseqData = scte[["RNA"]]@scale.data, scaled = TRUE, 
#                       gs = gs_list$gs_positive, gs2 = gs_list$gs_negative) 

# # merge by cluster
# cL_resutls = do.call("rbind", lapply(unique(scte@meta.data$seurat_clusters), function(cl){
#     es.max.cl = sort(rowSums(es.max[ ,rownames(scte@meta.data[scte@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
#     head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(scte@meta.data$seurat_clusters==cl)), 10)
# }))
# sctype_scores = cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)  

# # set low-confident (low ScType score) clusters to "unknown"
# sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells/4] = "Unknown"


# scte@meta.data$customclassif = ""
# for(j in unique(sctype_scores$cluster)){
#   cl_type = sctype_scores[sctype_scores$cluster==j,]; 
#   scte@meta.data$customclassif[scte@meta.data$seurat_clusters == j] = as.character(cl_type$type[1])
# }

# ## save cell type
# cell_types<-scte[['customclassif']]